# This is a basic workflow to help you get started with Actions

name: price check every day

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '1 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  auto-actions:
    name: price check everyday
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout codes
        uses: actions/checkout@v3
      # 安装python3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # 安装python的外部依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      # Runs a set of commands using the runners shell
      - name: run
        run: python ./main.py

      - name: send_email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_ACCOUNT }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Orders error
          to: ${{ secrets.MAIL_ADDRESS }}
          # Required sender full name (address can be skipped):
          from: ${{ secrets.MAIL_ACCOUNT }}
          secure: true
          body: We have some wrong orders.
          attachments: ./errorResult/error.csv
          priority: high
